### PR TITLE
added work around to retrieve feed url with error code 403 forbidden

### PR DESCRIPTION
**Pull request by adil-s**
the following feed URLS were throwing error code 403 forbidden:

* https://blogs.microsoft.com/accessibility?feed=rss2
* https://www.marcozehe.de/rss/

I have added  user agent in the request header to fake feed reader as browser. so it doesn't throw error. 
could someone verify the patch?
pardon me if I'm not following any etticates  as I'm new to contributing. this is my first pull request.

### CODE REVIEW

**Review by nvdaes — COMMENTED** [review]
Thanks for your contribution! Here is some feedback:

Firstly, I like the idea of providing an user agent to support more feeds.

Other comments:

- Seems you have linted code according to .vscode, right? This causes more than 1000 lines changed in the Python file, though meaningful changes are shorter. So, to make possible a better review, could you try not to lint the code in this PR? I think I should lint it automatically for example with GitHub Actions. Especially, let's use tabs instead of spaces in Python files, respecting rules of NVDA. This makes it more readable with screen readers, since it's easier to move the cursor by tabs than by spaces.

- Seems there may be some changes in the .mo file for arabic translation. Let me know if I'm wrong. When I run scons, an error is raised and I'm notified that the add-on cannot be built.

Suggestion: let's focus this PR on providing an user agent, just changing the Python file accordingly. Also, you can add your name in the copyright headers.

Lastly, here is a webpage with other user agents, in case you prefer to choose a different one:

http://www.useragentstring.com/pages/useragentstring.php?typ=Feed%20Reader

Kind regards

**Comment by nvdaes** [comment]
Hello, I wrote:

> Seems there may be some changes in the .mo file for arabic translation. Let me know if I'm wrong. 

In fact I made a mistake with this appreciation. I'm getting the same error on PR #6 

Thanks again for your work, @adil-s

**Comment by adil-s** [comment]
here are my observation.
* the commit which I made yesterday doesn't show up this error. it built fine.
* tried checking out your last commit with hash commit 9ee783a2639ec9ed8aae0105a6f5330dbb4d4536                                                                                                                         on a new branch 
* made necessary changes and tryed compiling again 
* the error start showing up 


if you have found the cause, I would like to know what went wrong.

**Comment by nvdaes** [comment]
Oh, if this is the commit that produces the error, it's related to translated archives. @NVAccess is working to fix the translations system used for add-ons or will work on it. Not sure if fixing the system this error could be avoided.
You're closed the PR. I suppose you want me to include the changes made by me to add feedparser as user agent. In this case, I will do it waiting for your future contributions on this or other add-ons maintained by me.
Thanks

**Pull request closed without merging**
